# Generated by Django 5.1.4 on 2024-12-31 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gefi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='name of the currency')),
                ('symbol', models.CharField(max_length=30, verbose_name='symbol of the currency')),
            ],
        ),
        migrations.CreateModel(
            name='MovementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp when the register was created')),
                ('date_movement', models.DateField(verbose_name='date when the movement occurrent')),
                ('movemented_value', models.FloatField(verbose_name='value movemented')),
                ('observation', models.CharField(blank=True, max_length=500, verbose_name='observation about this movement')),
            ],
            options={
                'ordering': ['-registered_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodModel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='name of the payment method')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='benefitmodel',
            name='unique_name_benefited_constraint',
        ),
        migrations.RenameField(
            model_name='benefitmodel',
            old_name='benefited_model',
            new_name='benefited',
        ),
        migrations.AddField(
            model_name='benefitmodel',
            name='movimentation_categories',
            field=models.ManyToManyField(to='gefi.movimentationcategorymodel'),
        ),
        migrations.AddConstraint(
            model_name='benefitmodel',
            constraint=models.UniqueConstraint(fields=('name', 'benefited'), name='unique_name_benefited_constraint'),
        ),
        migrations.AddField(
            model_name='movementsmodel',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gefi.benefitmodel', verbose_name='associated benefit from this movement'),
        ),
        migrations.AddField(
            model_name='movementsmodel',
            name='benefited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gefi.benefitedmodel', verbose_name='benefited from this movement'),
        ),
        migrations.AddField(
            model_name='movementsmodel',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gefi.currencymodel', verbose_name='currency used in this movement'),
        ),
        migrations.AddField(
            model_name='movementsmodel',
            name='movimentation_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gefi.movimentationcategorymodel', verbose_name='category associated with this movement'),
        ),
        migrations.AddField(
            model_name='movementsmodel',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gefi.paymentmethodmodel', verbose_name='payment method of this movement'),
        ),
    ]
