# Generated by Django 5.1.4 on 2024-12-31 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gefi', '0002_currencymodel_movementsmodel_paymentmethodmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAccountBalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(verbose_name='current value in the account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gefi.currencymodel', verbose_name='currency of your balance')),
            ],
        ),
    ]
