# Generated by Django 5.1.4 on 2025-01-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gefi', '0004_movementsmodel_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benefitmodel',
            name='unique_name_benefited_constraint',
        ),
        migrations.RenameField(
            model_name='benefitmodel',
            old_name='benefited_category',
            new_name='benefit_category',
        ),
        migrations.AlterField(
            model_name='movimentationcategorymodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='the current category model is active or not'),
        ),
        migrations.AddConstraint(
            model_name='benefitmodel',
            constraint=models.UniqueConstraint(fields=('name', 'benefited', 'benefit_category'), name='unique_name_benefit_constraint'),
        ),
    ]
