# Generated by Django 5.1.4 on 2025-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gefi', '0005_remove_benefitmodel_unique_name_benefited_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitmodel',
            name='last_movement_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last time that the movement was done'),
        ),
    ]
